services:
  weaviate:
    image: semitechnologies/weaviate:1.25.4
    ports:
      - "8090:8080"
    environment:
      TRANSFORMERS_INFERENCE_API: "http://vectorizer:8080"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      ENABLE_MODULES: "text2vec-transformers"
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    # volumes:
    #   - weaviate_data:/var/lib/weaviate
    depends_on:
      - vectorizer

  vectorizer:
    build: ./vectorizer-proxy
    ports:
      - "8091:8080"
    environment:
      MODEL_NAME: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
      ENABLE_CUDA: "1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
